"""enable_rls_policies

Revision ID: 0002_rls_policies
Revises: 0001_initial_schema
Create Date: 2026-05-22

USAGE:
    After running `alembic revision --autogenerate -m "initial_schema"` and
    reviewing the generated file, create this file as the NEXT revision
    (update `Revises` to match the autogenerated revision ID).

    Then run:
        alembic upgrade head

PURPOSE:
    Alembic --autogenerate cannot detect PostgreSQL RLS policies.
    This migration manually applies all RLS enforcement statements
    using op.execute() for every tenant-scoped table.

TABLES COVERED:
    tenant_users, customers, property_listings, conversations, customer_reports

EXCLUDED:
    - tenants      : IS the tenant; RLS partition is meaningless here.
    - messages     : No tenant_id column; isolation via Conversation JOIN.

NOTE ON current_setting() SIGNATURE:
    current_setting('app.current_tenant_id', true)
    The `true` (missing_ok) flag prevents PostgreSQL from raising an error
    when the GUC is not set. Instead it returns NULL, which causes the
    USING clause to evaluate to false — correctly blocking all rows.
    This is safer than the variant without the flag.
"""
from __future__ import annotations

from alembic import op


# ─────────────────────────────────────────────────────────────────────────────
# Revision identifiers
# ─────────────────────────────────────────────────────────────────────────────
revision = "0002_rls_policies"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


# ─────────────────────────────────────────────────────────────────────────────
# Tenant-scoped tables that need RLS (order does not matter for RLS itself)
# ─────────────────────────────────────────────────────────────────────────────
_RLS_TABLES = [
    "tenant_users",
    "customers",
    "property_listings",
    "conversations",
    "customer_reports",
]

_POLICY_NAME = "tenant_isolation_policy"
_GUC = "app.current_tenant_id"


def upgrade() -> None:
    """
    Enable RLS on all tenant-scoped tables and create the isolation policy.

    The policy:
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)

    Blocks ALL rows when the GUC is not set (returns NULL → no match).
    Allows ONLY rows whose tenant_id matches the injected GUC value.
    """
    for table in _RLS_TABLES:
        # Step 1 — Enable RLS (allows superuser bypass by default)
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")

        # Step 2 — FORCE RLS so even the table owner (app DB role) is subject to it.
        # Without FORCE, the owning role bypasses RLS — a security hole.
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")

        # Step 3 — Create the isolation policy (idempotent with DROP IF EXISTS)
        op.execute(f"DROP POLICY IF EXISTS {_POLICY_NAME} ON {table};")
        op.execute(
            f"""
            CREATE POLICY {_POLICY_NAME} ON {table}
                USING (
                    tenant_id = current_setting('{_GUC}', true)::uuid
                );
            """
        )


def downgrade() -> None:
    """
    Remove RLS policies and disable Row-Level Security on all covered tables.

    Order: drop policy first, then disable — avoids "policy depends on RLS" errors.
    """
    for table in _RLS_TABLES:
        op.execute(
            f"DROP POLICY IF EXISTS {_POLICY_NAME} ON {table};"
        )
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;")
