"""Add clerk_id

Revision ID: 9e62a0b74221
Revises: c988f1befa51
Create Date: 2026-08-12 05:18:48.753517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e62a0b74221'
down_revision: Union[str, None] = 'c988f1befa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_users', sa.Column('clerk_id', sa.String(length=100), nullable=True, comment='Clerk User ID (user_2abcdef...)'))
    op.create_index(op.f('ix_tenant_users_clerk_id'), 'tenant_users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_users_clerk_id'), table_name='tenant_users')
    op.drop_column('tenant_users', 'clerk_id')
    # ### end Alembic commands ###
