"""Add fal_license_number and phone_number

Revision ID: c988f1befa51
Revises: 0005_add_engagement_score
Create Date: 2026-06-20 23:55:12.015236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c988f1befa51'
down_revision: Union[str, None] = '0005_add_engagement_score'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.UUID(),
               comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('conversations', 'assigned_agent_id',
               existing_type=sa.UUID(),
               comment='NULL = AI active; set when human takes over',
               existing_nullable=True)
    op.alter_column('conversations', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='Originating channel',
               existing_nullable=False)
    op.alter_column('conversations', 'platform_conversation_id',
               existing_type=sa.VARCHAR(length=200),
               comment='Platform-native thread/conversation ID for deduplication',
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Cached message count for pagination',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversations_platform_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_platform_conversation_id'), 'conversations', ['platform_conversation_id'], unique=False)
    op.alter_column('customer_reports', 'tenant_id',
               existing_type=sa.UUID(),
               comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('customer_reports', 's3_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='Permanent S3 object URL — serve via pre-signed URL in API',
               existing_nullable=True)
    op.alter_column('customer_reports', 'price_sar',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Amount charged in SAR',
               existing_nullable=True)
    op.alter_column('customer_reports', 'payment_reference',
               existing_type=sa.VARCHAR(length=200),
               comment='Gateway transaction ID (Moyasar / Tap)',
               existing_nullable=True)
    op.alter_column('customer_reports', 'is_delivered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True after the report PDF was sent to the customer',
               existing_nullable=False)
    op.alter_column('customer_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('customers', 'unified_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='E.164 phone number — golden identifier across all channels',
               existing_nullable=False)
    op.alter_column('customers', 'is_processing_restricted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='PDPL opt-out — if True, skip AI and route to human immediately',
               existing_nullable=False)
    op.alter_column('customers', 'is_vip',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'vcard_state',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               comment='State in the VCard follow-up drip sequence',
               existing_nullable=False)
    op.alter_column('customers', 'vault_s3_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment="S3 prefix for this customer's private document vault",
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_customers_engagement_score'), table_name='customers')
    op.create_index(op.f('ix_customers_engagement_score'), 'customers', ['engagement_score'], unique=False)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               comment="'customer' | 'ai_bot' | 'human_agent'",
               existing_nullable=False)
    op.alter_column('messages', 'agent_id',
               existing_type=sa.UUID(),
               comment="Set only when sender_type = 'human_agent'",
               existing_nullable=True)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'text_content',
               existing_type=sa.TEXT(),
               comment='Plaintext body or Whisper transcription of audio',
               existing_nullable=True)
    op.alter_column('messages', 's3_media_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='S3 URL for audio/image/video/document payloads',
               existing_nullable=True)
    op.alter_column('messages', 'platform_message_id',
               existing_type=sa.VARCHAR(length=200),
               comment='Platform-native message ID — used for deduplication',
               existing_nullable=True)
    op.alter_column('messages', 'llm_routing_tier',
               existing_type=sa.VARCHAR(length=10),
               comment='Routing tier that generated this response: L0–L3 | VAULT | HUMAN',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='LLM token cost for this message',
               existing_nullable=True)
    op.alter_column('messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='End-to-end generation latency in milliseconds',
               existing_nullable=True)
    op.alter_column('messages', 'delivery_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               comment="'PENDING' | 'SENT' | 'DELIVERED' | 'FAILED'",
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_listings', 'tenant_id',
               existing_type=sa.UUID(),
               comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('property_listings', 'rega_ad_number',
               existing_type=sa.VARCHAR(length=30),
               comment='REGA advertisement number (رقم الإعلان) — unique per tenant',
               existing_nullable=False)
    op.alter_column('property_listings', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('property_listings', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True only after REGA API confirms the ad number',
               existing_nullable=False)
    op.alter_column('property_listings', 'price',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Price in SAR',
               existing_nullable=True)
    op.alter_column('property_listings', 'description_ar',
               existing_type=sa.TEXT(),
               comment='Arabic description — embedded in Qdrant',
               existing_nullable=True)
    op.alter_column('property_listings', 'description_en',
               existing_type=sa.TEXT(),
               comment='English description — embedded in Qdrant',
               existing_nullable=True)
    op.alter_column('property_listings', 'qdrant_point_id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID string referencing the Qdrant vector point',
               existing_nullable=True)
    op.alter_column('property_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tenant_users', sa.Column('phone_number', sa.String(length=50), nullable=True, comment='User phone number'))
    op.alter_column('tenant_users', 'tenant_id',
               existing_type=sa.UUID(),
               comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('tenant_users', 'email',
               existing_type=sa.VARCHAR(length=254),
               comment='Login email — unique within tenant scope',
               existing_nullable=False)
    op.alter_column('tenant_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Argon2id / bcrypt hash — NEVER store plaintext',
               existing_nullable=False)
    op.alter_column('tenant_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tenant_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Primary key — RLS partition key referenced by all other tables',
               existing_nullable=False)
    op.alter_column('tenants', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Legal business name of the agency',
               existing_nullable=False)
    op.alter_column('tenants', 'fal_license_number',
               existing_type=sa.VARCHAR(length=50),
               comment='FAL license number — verified via REGA Broker Verification API',
               existing_nullable=False)
    op.alter_column('tenants', 'subscription_tier',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               comment='Subscription plan: economic | professional | enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               comment='Billing / access status',
               existing_nullable=False)
    op.alter_column('tenants', 'onboarding_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               comment='Tenant onboarding flow status',
               existing_nullable=False)
    op.alter_column('tenants', 'meta_access_token',
               existing_type=sa.TEXT(),
               comment='Meta WhatsApp/Omnichannel API Access Token',
               existing_nullable=True)
    op.alter_column('tenants', 'whatsapp_phone_number_id',
               existing_type=sa.VARCHAR(length=30),
               comment='Meta WhatsApp Business Phone Number ID',
               existing_nullable=True)
    op.alter_column('tenants', 'whatsapp_waba_id',
               existing_type=sa.VARCHAR(length=30),
               comment='Meta WhatsApp Business Account ID',
               existing_nullable=True)
    op.alter_column('tenants', 'max_ai_conversations',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Monthly AI conversation quota per subscription tier',
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tenants_fal_license_number_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_fal_license_number'), table_name='tenants')
    op.create_index(op.f('ix_tenants_fal_license_number'), 'tenants', ['fal_license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_fal_license_number'), table_name='tenants')
    op.create_index(op.f('ix_tenants_fal_license_number'), 'tenants', ['fal_license_number'], unique=False)
    op.create_unique_constraint(op.f('tenants_fal_license_number_key'), 'tenants', ['fal_license_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'max_ai_conversations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('500'),
               comment=None,
               existing_comment='Monthly AI conversation quota per subscription tier',
               existing_nullable=False)
    op.alter_column('tenants', 'whatsapp_waba_id',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Meta WhatsApp Business Account ID',
               existing_nullable=True)
    op.alter_column('tenants', 'whatsapp_phone_number_id',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Meta WhatsApp Business Phone Number ID',
               existing_nullable=True)
    op.alter_column('tenants', 'meta_access_token',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Meta WhatsApp/Omnichannel API Access Token',
               existing_nullable=True)
    op.alter_column('tenants', 'onboarding_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending_selection'::character varying"),
               comment=None,
               existing_comment='Tenant onboarding flow status',
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'trial'::character varying"),
               comment=None,
               existing_comment='Billing / access status',
               existing_nullable=False)
    op.alter_column('tenants', 'subscription_tier',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'economic'::character varying"),
               comment=None,
               existing_comment='Subscription plan: economic | professional | enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'fal_license_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='FAL license number — verified via REGA Broker Verification API',
               existing_nullable=False)
    op.alter_column('tenants', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Legal business name of the agency',
               existing_nullable=False)
    op.alter_column('tenants', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key — RLS partition key referenced by all other tables',
               existing_nullable=False)
    op.alter_column('tenant_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tenant_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tenant_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'agent'::character varying"),
               existing_nullable=False)
    op.alter_column('tenant_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Argon2id / bcrypt hash — NEVER store plaintext',
               existing_nullable=False)
    op.alter_column('tenant_users', 'email',
               existing_type=sa.VARCHAR(length=254),
               comment=None,
               existing_comment='Login email — unique within tenant scope',
               existing_nullable=False)
    op.alter_column('tenant_users', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.drop_column('tenant_users', 'phone_number')
    op.alter_column('property_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_listings', 'qdrant_point_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID string referencing the Qdrant vector point',
               existing_nullable=True)
    op.alter_column('property_listings', 'description_en',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='English description — embedded in Qdrant',
               existing_nullable=True)
    op.alter_column('property_listings', 'description_ar',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Arabic description — embedded in Qdrant',
               existing_nullable=True)
    op.alter_column('property_listings', 'price',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment='Price in SAR',
               existing_nullable=True)
    op.alter_column('property_listings', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='True only after REGA API confirms the ad number',
               existing_nullable=False)
    op.alter_column('property_listings', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'PENDING_VERIFICATION'::character varying"),
               existing_nullable=False)
    op.alter_column('property_listings', 'rega_ad_number',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='REGA advertisement number (رقم الإعلان) — unique per tenant',
               existing_nullable=False)
    op.alter_column('property_listings', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'delivery_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment="'PENDING' | 'SENT' | 'DELIVERED' | 'FAILED'",
               existing_nullable=True)
    op.alter_column('messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='End-to-end generation latency in milliseconds',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='LLM token cost for this message',
               existing_nullable=True)
    op.alter_column('messages', 'llm_routing_tier',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Routing tier that generated this response: L0–L3 | VAULT | HUMAN',
               existing_nullable=True)
    op.alter_column('messages', 'platform_message_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Platform-native message ID — used for deduplication',
               existing_nullable=True)
    op.alter_column('messages', 's3_media_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='S3 URL for audio/image/video/document payloads',
               existing_nullable=True)
    op.alter_column('messages', 'text_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Plaintext body or Whisper transcription of audio',
               existing_nullable=True)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.alter_column('messages', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Set only when sender_type = 'human_agent'",
               existing_nullable=True)
    op.alter_column('messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'customer' | 'ai_bot' | 'human_agent'",
               existing_nullable=False)
    op.drop_index(op.f('ix_customers_engagement_score'), table_name='customers')
    op.create_index(op.f('ix_customers_engagement_score'), 'customers', ['tenant_id', 'engagement_score'], unique=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'vault_s3_prefix',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="S3 prefix for this customer's private document vault",
               existing_nullable=True)
    op.alter_column('customers', 'vcard_state',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'STATE_NEW'::character varying"),
               comment=None,
               existing_comment='State in the VCard follow-up drip sequence',
               existing_nullable=False)
    op.alter_column('customers', 'is_vip',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('customers', 'is_processing_restricted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='PDPL opt-out — if True, skip AI and route to human immediately',
               existing_nullable=False)
    op.alter_column('customers', 'unified_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='E.164 phone number — golden identifier across all channels',
               existing_nullable=False)
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.alter_column('customer_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_reports', 'is_delivered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='True after the report PDF was sent to the customer',
               existing_nullable=False)
    op.alter_column('customer_reports', 'payment_reference',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Gateway transaction ID (Moyasar / Tap)',
               existing_nullable=True)
    op.alter_column('customer_reports', 'price_sar',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='Amount charged in SAR',
               existing_nullable=True)
    op.alter_column('customer_reports', 's3_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Permanent S3 object URL — serve via pre-signed URL in API',
               existing_nullable=True)
    op.alter_column('customer_reports', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_platform_conversation_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_platform_id'), 'conversations', ['platform_conversation_id'], unique=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last mutation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation timestamp (TIMESTAMPTZ)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Cached message count for pagination',
               existing_nullable=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ai_active'::character varying"),
               existing_nullable=False)
    op.alter_column('conversations', 'platform_conversation_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Platform-native thread/conversation ID for deduplication',
               existing_nullable=True)
    op.alter_column('conversations', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Originating channel',
               existing_nullable=False)
    op.alter_column('conversations', 'assigned_agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = AI active; set when human takes over',
               existing_nullable=True)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='RLS partition key — must match app.current_tenant_id',
               existing_nullable=False)
    # ### end Alembic commands ###
